name: Check Version Consistency

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install toml

      - name: Extract version from pyproject.toml
        id: pyproject-version
        run: |
          PYPROJECT_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version']")
          echo "Version in pyproject.toml: $PYPROJECT_VERSION"
          echo "pyproject_version=$PYPROJECT_VERSION" >> $GITHUB_OUTPUT

      - name: Extract version from _version.py
        id: version-py
        run: |
          VERSION_PY=$(grep -oP 'VERSION = "\K[^"]+' src/iduedu/_version.py)
          echo "Version in _version.py: $VERSION_PY"
          echo "version_py=$VERSION_PY" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          if [ "${{ steps.pyproject-version.outputs.pyproject_version }}" != "${{ steps.version-py.outputs.version_py }}" ]; then
            echo "Versions do not match!"
            echo "pyproject.toml: ${{ steps.pyproject-version.outputs.pyproject_version }}"
            echo "_version.py: ${{ steps.version-py.outputs.version_py }}"
            exit 1
          else
            echo "Versions match!"
          fi